### ISSUE TITLE
Ok to alter code to segment .jpg images?

### ISSUE THREAD

**Issue by smwoodman** [paradom/Threshold-MSER#6]
Hi, thanks for this great tool. 

I'm interested in using this tool to segment jpg images. While this is not currently supported in the code, it is easy to enable via small changes to the cpp files before building, as in [this fork](https://github.com/us-amlr/Threshold-MSER/commit/436e1be030251617f693797c5af5dbfa427b90ee)

I am fine with the output files still being png files, and thus the changes in the fork work for me. However, I wanted to check if this raised red flags for you, i.e. if segmenting jpgs was something that was intentionally left out of this toolbox?

**Comment by paradom** [comment]
Hi, sorry for not getting back to you! JPEGs have lossy compression so there is some information loss (which is why I wasn't using these). Everything should still work great segmenting JPEGs!

**Comment by smwoodman** [comment]
No worries, and thanks for the response. That makes sense - I mostly just wanted to check that there wasn't something else with jpegs that I wasn't thinking about.
